version: '2'
services:
    blockchainapp-app:
        image: blockchainapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blockchainapp-postgresql:5432/blockchainApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blockchainapp-postgresql:
        extends:
            file: postgresql.yml
            service: blockchainapp-postgresql
